name: Compile and Release LaTeX document

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download latest release assets
        uses: actions/download-artifact@v2
        with:
          repository: magnusdtd/sort-project
          path: ./exprimental_result
          name: images.zip
          name: result_tables.tex

      - name: Extract images.zip
        run: unzip ./exprimental_result/images.zip -d ./exprimental_result

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with: 
          working_directory: .
          root_file: main.tex

      - name: Rename PDF
        run: mv main.pdf Report.pdf

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env: 
          GITHUB_TOKEN: ${{ secrets.magnus_token }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: True
          prerelease: True

      - name: Set upload_url output
        run: echo "upload_url=${{ steps.create_release.outputs.upload_url }}" >> $GITHUB_ENV

      - name: Upload release artifact
        id: upload-release-artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.magnus_token }}
        with:
          upload_url: ${{ env.upload_url }}
          asset_path: ./Report.pdf
          asset_name: Report.pdf
          asset_content_type: application/pdf